package java_universitylibrary_db;
import javax.swing.table.DefaultTableModel;

public class Authors extends PopUpJpanel {

    public Authors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridAuthors = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        jButtFind = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButCheng = new javax.swing.JButton();
        DeleteButtom = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GridAuthors.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(GridAuthors);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Όνομα :");

        jButtFind.setText("Αναζήτηση");
        jButtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtFindActionPerformed(evt);
            }
        });

        jButton3.setText("Εισαγωγη");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButCheng.setText("Διόρθωση");
        jButCheng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButChengActionPerformed(evt);
            }
        });

        DeleteButtom.setText("Διαγραφή");
        DeleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtFind)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButCheng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButtom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtFind)
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCheng)
                    .addComponent(DeleteButtom)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.getPopupWin().actionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        FetchAuthor();
    }//GEN-LAST:event_formAncestorAdded

    private void jButtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtFindActionPerformed
        FetchAuthor();
    }//GEN-LAST:event_jButtFindActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AuthorUPD upd = new AuthorUPD();
        upd.setAction(PopUpJpanel.FormActionType.Insert);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Συγγραφέας ",upd);
        ppp.setSize(250, 200);
        FetchAuthor();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButChengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButChengActionPerformed
        int row = this.GridAuthors.getSelectedRow();
        if (row < 0 ){return;}
        DefaultTableModel model = (DefaultTableModel) this.GridAuthors.getModel();
        AuthorUPD upd = new AuthorUPD();
        upd.setPKValue( model.getValueAt(row,0).toString());
        upd.setAction(PopUpJpanel.FormActionType.Update);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Συγγραφέας",upd);
        ppp.setSize(250, 200);
        FetchAuthor();
    }//GEN-LAST:event_jButChengActionPerformed

    private void DeleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtomActionPerformed

        int row = this.GridAuthors.getSelectedRow();
        if (row < 0 ){return;}
        DefaultTableModel model = (DefaultTableModel) this.GridAuthors.getModel();
        AuthorUPD upd = new AuthorUPD();
        upd.setPKValue( model.getValueAt(row,0).toString());
        upd.setAction(PopUpJpanel.FormActionType.Delete);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Συγγραφέας",upd);
        ppp.setSize(250, 200);
        FetchAuthor();

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtomActionPerformed

       private void FetchAuthor(){
       try{
            String[] ColumnNames   = new String[]{ "α/α","Συγγραφέας"};
            String sql = "SELECT AUTHORID, NAME FROM author WHERE UPPER(NAME) like ? ";
            String[] parameter = new String[] {"%"+this.TxtName.getText().toUpperCase().trim()+ "%" };
            this.GridAuthors.setModel(ConnectDb.DbDefaultTableModel(ColumnNames, sql, parameter));
            this.GridAuthors.setRowSelectionInterval(0,0);
         }
        catch(DataException ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }
    }
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButtom;
    private javax.swing.JTable GridAuthors;
    private javax.swing.JTextField TxtName;
    private javax.swing.JButton jButCheng;
    private javax.swing.JButton jButtFind;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
