/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_universitylibrary_db;

import javax.swing.table.DefaultTableModel;

public class Brands extends PopUpJpanel {

    /**
     * Creates new form Category
     */
    public Brands() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridBrands = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        jButtFind = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButCheng = new javax.swing.JButton();
        DeleteButtom = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GridBrands.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(GridBrands);

        jLabel1.setText("Κατηγορία :");

        jButtFind.setText("Αναζήτηση");
        jButtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtFindActionPerformed(evt);
            }
        });

        jButton3.setText("Εισαγωγή");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButCheng.setText("Διόρθωση");
        jButCheng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButChengActionPerformed(evt);
            }
        });

        DeleteButtom.setText("Διαγραφή");
        DeleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButCheng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButtom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtFind)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCheng)
                    .addComponent(DeleteButtom)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.getPopupWin().actionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        FetchCategory();
    }//GEN-LAST:event_formAncestorAdded

    private void jButtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtFindActionPerformed
        FetchCategory();
    }//GEN-LAST:event_jButtFindActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BrandsUpd upd = new BrandsUpd();
        upd.setAction(PopUpJpanel.FormActionType.Insert);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Κατηγορίας",upd);
        ppp.setSize(250, 200);
        FetchCategory();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButChengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButChengActionPerformed
        int row = this.GridBrands.getSelectedRow();
        if (row < 0 ){return;}
        DefaultTableModel model = (DefaultTableModel) this.GridBrands.getModel();
        BrandsUpd upd = new BrandsUpd();
        upd.setPKValue( model.getValueAt(row,0).toString());
        upd.setAction(PopUpJpanel.FormActionType.Update);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Κατηγορίας",upd);
        ppp.setSize(250, 200);
        FetchCategory();
    }//GEN-LAST:event_jButChengActionPerformed

    private void DeleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtomActionPerformed

        int row = this.GridBrands.getSelectedRow();
        if (row < 0 ){return;}
        DefaultTableModel model = (DefaultTableModel) this.GridBrands.getModel();
        BrandsUpd upd = new BrandsUpd();
        upd.setPKValue( model.getValueAt(row,0).toString());
        upd.setAction(PopUpJpanel.FormActionType.Delete);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Προσθήκη Κατηγορίας",upd);
        ppp.setSize(250, 200);
        FetchCategory();

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtomActionPerformed

       private void FetchCategory(){
       try{
            String[] ColumnNames   = new String[]{ "α/α","Κατηγορια"};

            String sql = "SELECT BRANDSID,BRANDS.NAME \n" +
                        "FROM BRANDS \n" +
                        "where UPPER(BRANDS.NAME) like ? ";
            String[] parameter = new String[] {"%"+this.TxtName.getText().toUpperCase().trim()+ "%" };
            this.GridBrands.setModel(ConnectDb.DbDefaultTableModel(ColumnNames, sql, parameter));
            this.GridBrands.setRowSelectionInterval(0,0);
         }
        catch(DataException ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }
    }
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButtom;
    private javax.swing.JTable GridBrands;
    private javax.swing.JTextField TxtName;
    private javax.swing.JButton jButCheng;
    private javax.swing.JButton jButtFind;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
