/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_universitylibrary_db;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class CommandsBorrowing extends javax.swing.JInternalFrame  {

    /**
     * Creates new form CommandsBorrowing
     */
    public CommandsBorrowing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCustomers = new javax.swing.JTextField();
        ButFind = new javax.swing.JButton();
        BtInsertCommand = new javax.swing.JButton();
        Table_Books = new javax.swing.JScrollPane();
        GridOrders = new javax.swing.JTable();
        BtEnablecommand = new javax.swing.JButton();
        ButReturn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Εντολές δανεισμού");
        setToolTipText("");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Τίτλος :");
        jLabel1.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Δικαιούμενος :");

        ButFind.setText("Αναζήτηση");
        ButFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFindActionPerformed(evt);
            }
        });

        BtInsertCommand.setText("Καταχώριση δανεισμού");
        BtInsertCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInsertCommandActionPerformed(evt);
            }
        });

        GridOrders.setAutoCreateRowSorter(true);
        GridOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_Books.setViewportView(GridOrders);

        BtEnablecommand.setText("Ενεργοποίηση  δανεισμού");
        BtEnablecommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEnablecommandActionPerformed(evt);
            }
        });

        ButReturn.setText("Επιστροφή βιβλίου");
        ButReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Table_Books)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButFind))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtInsertCommand)
                                .addGap(18, 18, 18)
                                .addComponent(BtEnablecommand)
                                .addGap(18, 18, 18)
                                .addComponent(ButReturn)))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtInsertCommand)
                    .addComponent(BtEnablecommand)
                    .addComponent(ButReturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Table_Books, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFindActionPerformed
        FetchOrdesToTable();
    }//GEN-LAST:event_ButFindActionPerformed

    private void BtInsertCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInsertCommandActionPerformed
        CommandsUPD upd = new CommandsUPD();
        upd.setAction(PopUpJpanel.FormActionType.Insert);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Δημιουργία Εντολής",upd);
        FetchOrdesToTable();
    }//GEN-LAST:event_BtInsertCommandActionPerformed

    private void BtEnablecommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEnablecommandActionPerformed
        int row = this.GridOrders.getSelectedRow();
        if (row < 0 ){return ;} 
        DefaultTableModel model = (DefaultTableModel) this.GridOrders.getModel();
        CommandsUPD upd = new CommandsUPD();
        upd.setPKValue( model.getValueAt(row,0).toString());
        upd.setAction(PopUpJpanel.FormActionType.Update);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,"Ενεργοποιηση εντολής",upd);
        FetchOrdesToTable();
    }//GEN-LAST:event_BtEnablecommandActionPerformed

    private void ButReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButReturnActionPerformed
        String copyid ="";
        String orderid ="";
        int row = this.GridOrders.getSelectedRow();
        if (row < 0 ){return ;}      
        DefaultTableModel model = (DefaultTableModel) this.GridOrders.getModel();
        orderid = model.getValueAt(row,0).toString();
        copyid =  model.getValueAt(row,3).toString();
       
        
        ConnectDb con = new ConnectDb();
         String sql ="";
         String sqlCom ="";
         if ( copyid.trim().length() > 0 )
         {
            sql ="UPDATE ORDERS SET END_DATE ='" +new SimpleDateFormat("yyyy-MM-dd").format(new Date())+ "', \n"
                    + "RETURNFLG =1 \n"
                    + "WHERE ORDERID = "+orderid;
            sqlCom ="UPDATE copies SET FREEFLAG = 0  \n"+
            "WHERE COPYID ="+copyid; 
         }
         try{
             con.UpdateQuery(sql);
             if (sqlCom.trim().length() > 0)
             {
                  con.UpdateQuery(sqlCom);
             }
             con.Close();
             FetchOrdesToTable();
         }
         catch(DataException ex )
         {
             String mes = ex.getMessage()+"\n"+ex.getCause().getMessage();
             MsgBox.error(mes,ex.getMessage());
         }

    }//GEN-LAST:event_ButReturnActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
            ButReturn.setEnabled(false);
            BtEnablecommand.setEnabled(false);
    }//GEN-LAST:event_formAncestorAdded

    void FetchOrdesToTable()
    {
        java.util.ArrayList<String> ListParam = new java.util.ArrayList<String>();
        String[] parameter = null;
 
        String[] ColumnName = new String[]{"Εντολή","Δικαιούμενος δανεισμού", "Τίτλος βιβλίου ","Αντίγραφο"
                      ,"Εκκρεμής","Ημ.Εντολής ","Ημ.Επιστροφής","Επεστράφη"," "," "};
        String sql = "SELECT ORDERS.ORDERID,CUSTOMERS.NAME,BOOKS.TITLE,COPIES.COPYID,\n" +
                    "CASE WHEN ORDERS.ACTIVE =0 THEN 'Ναι' else 'Οχι' END AS act  ,\n" +
                    "ORDERS.START_DATE,\n" +
                    "ORDERS.END_DATE,\n" +
                    "CASE WHEN ORDERS.RETURNFLG =1 THEN 'Ναι' else 'Οχι' END AS ret  ,\n" +
                    "ORDERS.RETURNFLG,\n" +
                    "ORDERS.ACTIVE \n" +
                    "FROM ORDERS \n" +
                    "INNER JOIN CUSTOMERS ON CUSTOMERS.CUSTOMERSID = ORDERS.CUSTOMERSID\n" +
                    "INNER JOIN BOOKS ON BOOKS.ISBN = ORDERS.ISBN\n" +
                    "LEFT JOIN COPIES ON COPIES.COPYID = ORDERS.COPYID \n"; 
        if (this.TxtTitle.getText().length()>0)
        {
            if (ListParam.isEmpty()){
                sql +="WHERE UPPER(BOOKS.TITLE) like ?  \n";
            }
            else{
                 sql +="AND UPPER(BOOKS.TITLE) like ?  \n";
            }
            ListParam.add("%"+this.TxtTitle.getText().toUpperCase().trim()+ "%");
        }
        if (this.TxtCustomers.getText().length()>0)
        {
            if (ListParam.isEmpty()){
                sql +="WHERE UPPER(CUSTOMERS.NAME) like ?  \n";
            }
            else{
                 sql +="AND UPPER(CUSTOMERS.NAME) like ?  \n";
            }           
            ListParam.add("%"+this.TxtCustomers.getText().toUpperCase().trim()+ "%");
        }
        if (ListParam.size() > 0)
        {
            parameter = new String[ListParam.size()];
            for (int i = 0 ; i < ListParam.size(); i++ )
            {
                parameter[i] = ListParam.get(i);
            }
        }
        sql += "ORDER BY ORDERS.ACTIVE ,ORDERS.START_DATE ";
        try{
            this.GridOrders.setModel(ConnectDb.DbDefaultTableModel(ColumnName, sql,parameter ));
            GridOrders.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    BtEnablecommand.setEnabled(false);
                    ButReturn.setEnabled(false);
                    if (GridOrders.getSelectedRow() >=0 ){
                    String val = GridOrders.getValueAt(GridOrders.getSelectedRow(),8).toString();
                    
                    if (val.trim().length() >0 && Integer.parseInt(val) ==0)
                    {
                        ButReturn.setEnabled(true);
                    }
                     val = GridOrders.getValueAt(GridOrders.getSelectedRow(),9).toString();
                    if (val.trim().length() >0 && Integer.parseInt(val) ==0)
                    {
                        BtEnablecommand.setEnabled(true);
                        ButReturn.setEnabled(false);
                    }
                  }
               }
            });
            this.GridOrders.setRowSelectionInterval(0,0);
            this.GridOrders.getColumnModel().getColumn(0).setMinWidth(60);
            this.GridOrders.getColumnModel().getColumn(0).setMaxWidth(60);
            this.GridOrders.getColumnModel().getColumn(0).setWidth(60);

            this.GridOrders.getColumnModel().getColumn(3).setMinWidth(60);
            this.GridOrders.getColumnModel().getColumn(3).setMaxWidth(60);
            this.GridOrders.getColumnModel().getColumn(3).setWidth(60);
            this.GridOrders.getColumnModel().getColumn(4).setMinWidth(60);
            this.GridOrders.getColumnModel().getColumn(4).setMaxWidth(60);
            this.GridOrders.getColumnModel().getColumn(4).setWidth(60);  
            
            this.GridOrders.getColumnModel().getColumn(5).setMinWidth(90);
            this.GridOrders.getColumnModel().getColumn(5).setMaxWidth(90);
            this.GridOrders.getColumnModel().getColumn(5).setWidth(90);  

            this.GridOrders.getColumnModel().getColumn(6).setMinWidth(100);
            this.GridOrders.getColumnModel().getColumn(6).setMaxWidth(100);
            this.GridOrders.getColumnModel().getColumn(6).setWidth(100);  
            
            this.GridOrders.getColumnModel().getColumn(7).setMinWidth(80);
            this.GridOrders.getColumnModel().getColumn(7).setMaxWidth(80);
            this.GridOrders.getColumnModel().getColumn(7).setWidth(80);  
            
            this.GridOrders.getColumnModel().getColumn(8).setMinWidth(0);
            this.GridOrders.getColumnModel().getColumn(8).setMaxWidth(0);
            this.GridOrders.getColumnModel().getColumn(8).setWidth(0);              
            
            this.GridOrders.getColumnModel().getColumn(9).setMinWidth(0);
            this.GridOrders.getColumnModel().getColumn(9).setMaxWidth(0);
            this.GridOrders.getColumnModel().getColumn(9).setWidth(0);              
            
            
        }
        catch(DataException  ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            
            MsgBox.error(mes,ex.getMessage());
        }
   
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEnablecommand;
    private javax.swing.JButton BtInsertCommand;
    private javax.swing.JButton ButFind;
    private javax.swing.JButton ButReturn;
    private javax.swing.JTable GridOrders;
    private javax.swing.JScrollPane Table_Books;
    private javax.swing.JTextField TxtCustomers;
    private javax.swing.JTextField TxtTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
