/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_universitylibrary_db;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class CommandsUPD extends PopUpJpanel {

    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    public CommandsUPD() {
        initComponents();
        this.TxtCopyid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButCus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtCustomerid = new javax.swing.JTextField();
        LabelCusName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtISBN = new javax.swing.JTextField();
        ButBook = new javax.swing.JButton();
        LabelTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtCopyid = new javax.swing.JTextField();
        ButCopiesbook = new javax.swing.JButton();
        ButSave = new javax.swing.JButton();
        ButCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LabelStartDate = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ButCus.setText("Αναζήτηση");
        ButCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCusActionPerformed(evt);
            }
        });

        jLabel1.setText("Δανειζόμενος ");

        TxtCustomerid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCustomeridFocusLost(evt);
            }
        });
        TxtCustomerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCustomeridActionPerformed(evt);
            }
        });
        TxtCustomerid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCustomeridKeyTyped(evt);
            }
        });

        LabelCusName.setText(" ");

        jLabel2.setText("Βιβλιο");

        TxtISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtISBNFocusLost(evt);
            }
        });
        TxtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtISBNActionPerformed(evt);
            }
        });
        TxtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtISBNKeyTyped(evt);
            }
        });

        ButBook.setText("Αναζήτηση");
        ButBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBookActionPerformed(evt);
            }
        });

        LabelTitle.setText(" ");

        jLabel3.setText("Αντίγραφο");

        TxtCopyid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCopyidFocusLost(evt);
            }
        });
        TxtCopyid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCopyidActionPerformed(evt);
            }
        });
        TxtCopyid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCopyidKeyTyped(evt);
            }
        });

        ButCopiesbook.setText("Αναζήτηση");
        ButCopiesbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCopiesbookActionPerformed(evt);
            }
        });

        ButSave.setText("Save");
        ButSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSaveActionPerformed(evt);
            }
        });

        ButCancel.setText("Cancel");
        ButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Ημερομηνία Εντολής :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButSave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCustomerid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(TxtCopyid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(TxtISBN, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButCus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButCancel)
                                .addComponent(ButCopiesbook)))))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ButCus)
                    .addComponent(LabelCusName)
                    .addComponent(TxtCustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ButBook)
                    .addComponent(LabelTitle)
                    .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButCopiesbook)
                        .addComponent(TxtCopyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSave)
                    .addComponent(ButCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCusActionPerformed
        Customers cus = new Customers();
        cus.setSelectedButton(true);
        cus.setVisible(true);
        String ret = "";
//        PopUpJInternalFrame ppp = new PopUpJInternalFrame(PopUpJInternalFrame.GetFrame(this),"Δικαιούμενος δανεισμού",cus);
        PopUpJInternalFrame ppp = new PopUpJInternalFrame(this.GetFrame(),"Δικαιούμενος δανεισμού",cus);
        this.TxtCustomerid.setText(cus.getSelectValue());
        GetCustomer();
    }//GEN-LAST:event_ButCusActionPerformed

    private void TxtCustomeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCustomeridActionPerformed
        GetCustomer();
    }//GEN-LAST:event_TxtCustomeridActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        Getorders();
    }//GEN-LAST:event_formAncestorAdded

    private void TxtCustomeridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCustomeridFocusLost
        if (this.TxtCustomerid.getText().trim().length()> 0)
        {
            GetCustomer();
        }
    }//GEN-LAST:event_TxtCustomeridFocusLost

    private void TxtCustomeridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCustomeridKeyTyped
       char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtCustomeridKeyTyped

    private void TxtISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtISBNFocusLost
        if (this.TxtISBN.getText().trim().length()> 0)
        {
            GetBook();
        }
    }//GEN-LAST:event_TxtISBNFocusLost

    private void TxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtISBNActionPerformed
            GetBook();
    }//GEN-LAST:event_TxtISBNActionPerformed

    private void TxtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtISBNKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtISBNKeyTyped

    private void ButBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBookActionPerformed
        Books book = new Books();
        book.setSelectedButton(true);
        book.setVisible(true);
        String ret = "";
        PopUpJInternalFrame ppp = new PopUpJInternalFrame(this.GetFrame(),"Βιβλία",book);
        this.TxtISBN.setText(book.getSelectValue());
        GetBook();
        
    }//GEN-LAST:event_ButBookActionPerformed

    private void TxtCopyidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCopyidFocusLost
        
        
        
        
    }//GEN-LAST:event_TxtCopyidFocusLost

    private void TxtCopyidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCopyidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCopyidActionPerformed

    private void TxtCopyidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCopyidKeyTyped
         char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtCopyidKeyTyped

    private void ButCopiesbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCopiesbookActionPerformed
        if (this.TxtISBN.getText().trim().length() ==0) {return ;} 
        SelectCopiesBook upd = new SelectCopiesBook();
        upd.setPKValue(this.TxtISBN.getText());
        upd.setAction(PopUpJpanel.FormActionType.Select);
        PopUpMondalWindow ppp = new PopUpMondalWindow(this,this.LabelTitle.getText() ,upd);  
        this.TxtCopyid.setText(upd.getSelectValue());
        GetBookCopies();
    }//GEN-LAST:event_ButCopiesbookActionPerformed

    private void ButSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSaveActionPerformed
        if (this.getAction() == PopUpJpanel.FormActionType.Insert)
        {
            if (this.TxtCustomerid.getText().trim().length() == 0)
            {
                this.TxtCustomerid.setFocusable(true);
                return;
            }
            if (this.TxtISBN.getText().trim().length() == 0)
            {
                this.TxtISBN.setFocusable(true);
                return;
            }            
            ConnectDb con = new ConnectDb();
            String sqlCom ="";
            String sql ="INSERT INTO ORDERS(CUSTOMERSID,ISBN,START_DATE, RETURNFLG ,COPYID,ACTIVE) \n"
                    + "VALUES ( "+this.TxtCustomerid.getText()+","+this.TxtISBN.getText()+ ","+
                    "'"+new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "',0,";
            if ( this.TxtCopyid.getText().trim().length() > 0 )
            {
                sql +=this.TxtCopyid.getText()+",1)";
                sqlCom ="UPDATE copies SET FREEFLAG = 1 \n"+
                      "WHERE COPYID ="+ this.TxtCopyid.getText(); 
            }
            else
            {
                 sql +="null,0)";
            }
            try{
                con.UpdateQuery(sql);
                
                if (sqlCom.trim().length() > 0)
                {
                     con.UpdateQuery(sqlCom);
                }
                con.Close();
            }
            catch(DataException ex )
            {
                String mes = ex.getMessage()+"\n"+ex.getCause().getMessage();
                MsgBox.error(mes,ex.getMessage());
            }
        }
        if (this.getAction() == PopUpJpanel.FormActionType.Update)
        {
            ConnectDb con = new ConnectDb();
            String sql ="";
            String sqlCom ="";
            if ( this.TxtCopyid.getText().trim().length() > 0 )
            {
               sql ="UPDATE ORDERS SET COPYID = "+this.TxtCopyid.getText()+",ACTIVE = 1 \n";
               sql +="WHERE ORDERID = "+this.getPKValue();
               sqlCom ="UPDATE copies SET FREEFLAG = 1 \n"+
               "WHERE COPYID ="+ this.TxtCopyid.getText(); 
            }
            try{
                con.UpdateQuery(sql);
                if (sqlCom.trim().length() > 0)
                {
                     con.UpdateQuery(sqlCom);
                }
                con.Close();
            }
            catch(DataException ex )
            {
                String mes = ex.getMessage()+"\n"+ex.getCause().getMessage();
                MsgBox.error(mes,ex.getMessage());
            }
        }
        this.getPopupWin().actionPerformed(evt);
    }//GEN-LAST:event_ButSaveActionPerformed

    private void ButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelActionPerformed
        this.getPopupWin().actionPerformed(evt);
    }//GEN-LAST:event_ButCancelActionPerformed
    
    private void GetCustomer(){
        ConnectDb con = new ConnectDb();
        String sql = "SELECT CUSTOMERSID, NAME FROM customers WHERE CUSTOMERSID = ?";
        String[] parameter = new String[]{this.TxtCustomerid.getText()};
        try{
            ResultSet rs =  con.ExecuteQuery(sql,parameter);
            while(rs.next()){
              this.TxtCustomerid.setText(rs.getString("CUSTOMERSID"));
              this.LabelCusName.setText(rs.getString("NAME"));
            }
            con.Close();
        }
        catch(DataException |SQLException  ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }    
    }
    
    private void GetBook(){
        ConnectDb con = new ConnectDb();
        String sql = "SELECT ISBN, TITLE FROM BOOKS WHERE ISBN = ?";
        String[] parameter = new String[]{this.TxtISBN.getText()};
        try{
            ResultSet rs =  con.ExecuteQuery(sql,parameter);
            while(rs.next()){
              this.TxtISBN.setText(rs.getString("ISBN"));
              this.LabelTitle.setText(rs.getString("TITLE"));
            }
            con.Close();
            GetBookCopies();
        }
        catch(DataException |SQLException  ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }    
    }

    private void GetBookCopies(){
        if (this.TxtCopyid.getText().trim().length()== 0)
        {
            return;
        }
        java.util.ArrayList<String> ListParam = new java.util.ArrayList<String>();
        String[] parameter = null;         
        ListParam.add(this.TxtISBN.getText());
        ConnectDb con = new ConnectDb();
        String sql = "SELECT COPYID ,ISBN  FROM copies WHERE ISBN = ? \n";
               sql += "and COPYID = ? \n";
        ListParam.add(this.TxtCopyid.getText());
        if (ListParam.size() > 0)
        {
            parameter = new String[ListParam.size()];
            for (int i = 0 ; i < ListParam.size(); i++ )
            {
                parameter[i] = ListParam.get(i);
            }
        }
        try{
            this.TxtCopyid.setText("");
            ResultSet rs =  con.ExecuteQuery(sql,parameter);
            while(rs.next()){
              this.TxtCopyid.setText(rs.getString("COPYID"));
            }
            con.Close();
        }
        catch(DataException |SQLException  ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }    
    }
   
    private void Getorders()
    {
        if (this.getAction() == FormActionType.Insert ){
            Date date = new Date();
            this.LabelStartDate.setText(dateFormat.format(date)); //2014/08/06 15:59:48            
            return;
        }
        ConnectDb con = new ConnectDb();
        String sql = "SELECT ORDERS.ORDERID, ORDERS.CUSTOMERSID, CUSTOMERS.NAME, \n" +
                    "ORDERS.ISBN, BOOKS.TITLE,COPIES.COPYID,\n" +
                    "CASE WHEN ORDERS.ACTIVE =0 THEN 'Ναι' else 'Οχι' END AS EE  ,\n" +
                    "ORDERS.START_DATE,\n" +
                    "ORDERS.END_DATE,\n" +
                    "ORDERS.RETURNFLG,\n" +
                    "ORDERS.ACTIVE \n" +
                    "FROM ORDERS \n" +
                    "INNER JOIN CUSTOMERS ON CUSTOMERS.CUSTOMERSID = ORDERS.CUSTOMERSID\n" +
                    "INNER JOIN BOOKS ON BOOKS.ISBN = ORDERS.ISBN\n" +
                    "LEFT JOIN COPIES ON COPIES.COPYID = ORDERS.COPYID \n"+
                    "where ORDERS.ORDERID =? ";
        String[] parameter = new String[]{this.getPKValue()};
        try{
            ResultSet rs =  con.ExecuteQuery(sql,parameter);
            while(rs.next()){
              this.TxtCustomerid.setText(rs.getString("CUSTOMERSID"));
              this.LabelCusName.setText(rs.getString("NAME"));
              this.TxtISBN.setText(rs.getString("ISBN"));
              this.LabelTitle.setText(rs.getString("TITLE"));
              this.TxtCopyid.setText(rs.getString("COPYID"));
              this.LabelStartDate.setText(dateFormat.format(rs.getDate("START_DATE")));
            }
            con.Close();
            this.TxtCustomerid.setEnabled(false);
            this.ButCus.setEnabled(false);
            this.TxtISBN.setEnabled(false);
            this.ButBook.setEnabled(false);
        }
        
        
        
        catch(DataException |SQLException  ex )
        {
            String mes = ex.getMessage()+"\n"+ex.getCause().getMessage(); 
            MsgBox.error(mes,ex.getMessage());
        }    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButBook;
    private javax.swing.JButton ButCancel;
    private javax.swing.JButton ButCopiesbook;
    private javax.swing.JButton ButCus;
    private javax.swing.JButton ButSave;
    private javax.swing.JLabel LabelCusName;
    private javax.swing.JLabel LabelStartDate;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JTextField TxtCopyid;
    private javax.swing.JTextField TxtCustomerid;
    private javax.swing.JTextField TxtISBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
