/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_universitylibrary_db;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
/**
 *
 * @author Panagiotis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuCommands = new javax.swing.JMenu();
        jMenuItemCommand = new javax.swing.JMenuItem();
        jMenuLibrary = new javax.swing.JMenu();
        jMenuItemBooks = new javax.swing.JMenuItem();
        jMenuItemCustomers = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Πρόγραμμα Βιβλιοθήκης");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jMenuFile.setText("Αρχείο");

        jMenuExit.setText("Έξοδος");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenu.add(jMenuFile);

        jMenuCommands.setText("Εντολές");

        jMenuItemCommand.setText("Εντολές δανεισμού");
        jMenuItemCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCommandActionPerformed(evt);
            }
        });
        jMenuCommands.add(jMenuItemCommand);

        jMenu.add(jMenuCommands);

        jMenuLibrary.setText("Βιβλιοθήκη");

        jMenuItemBooks.setText("Βιβλία");
        jMenuItemBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBooksActionPerformed(evt);
            }
        });
        jMenuLibrary.add(jMenuItemBooks);

        jMenuItemCustomers.setText("Δικαιούμενοι δανεισμού");
        jMenuItemCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomersActionPerformed(evt);
            }
        });
        jMenuLibrary.add(jMenuItemCustomers);

        jMenu.add(jMenuLibrary);

        jMenu1.setText("Στατιστικά");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu.add(jMenu1);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuItemCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCommandActionPerformed
        NewWindow(new CommandsBorrowing());
    }//GEN-LAST:event_jMenuItemCommandActionPerformed

    private void jMenuItemBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBooksActionPerformed
         NewWindow(new Books());
    }//GEN-LAST:event_jMenuItemBooksActionPerformed

    private void jMenuItemCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomersActionPerformed
           NewWindow(new Customers());
    }//GEN-LAST:event_jMenuItemCustomersActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        NewWindow(new Statistics());
    }//GEN-LAST:event_jMenu1MouseClicked

    private void NewWindow(Component frm)
    {
       Dimension size = jDesktopPane1.getSize(); 
       JInternalFrame[] allframes = jDesktopPane1.getAllFrames(); 
       
       JInternalFrame old = null;
       for(JInternalFrame f : allframes )
       {
           if (f.getClass() == frm.getClass()) 
           {
              old = f;
           }
       }
       if (old != null)
       {
            old.moveToFront();
       }    
       else
       {
            frm.setSize(size);
            this.jDesktopPane1.add(frm);
            frm.setVisible(true);
       }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuCommands;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemBooks;
    private javax.swing.JMenuItem jMenuItemCommand;
    private javax.swing.JMenuItem jMenuItemCustomers;
    private javax.swing.JMenu jMenuLibrary;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
